linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - typecheck
    - unused
    - unconvert
    - gocyclo
    - goconst
    - gofumpt
    - goimports
    - misspell
    - stylecheck
issues:
  exclude-rules:
    - path: data/bv_master.go
      text: STRATEGIS
    - path: data/bv_master.go
      text: PROFESSIONAL
    - path: data/bv_master.go
      text: TEH
  exclude-files:
    - injector.go
    
run:
  build-tags:
    - wireinject
  tests: false
  timeout: 5m