// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/order_service.go

// Package mocksvc is a generated GoMock package.
package mocksvc

import (
	context "context"
	reflect "reflect"

	dto "github.com/gadhittana-01/book-go/dto"
	service "github.com/gadhittana-01/book-go/service"
	gomock "github.com/golang/mock/gomock"
)

// MockOrderSvc is a mock of OrderSvc interface.
type MockOrderSvc struct {
	ctrl     *gomock.Controller
	recorder *MockOrderSvcMockRecorder
}

// MockOrderSvcMockRecorder is the mock recorder for MockOrderSvc.
type MockOrderSvcMockRecorder struct {
	mock *MockOrderSvc
}

// NewMockOrderSvc creates a new mock instance.
func NewMockOrderSvc(ctrl *gomock.Controller) *MockOrderSvc {
	mock := &MockOrderSvc{ctrl: ctrl}
	mock.recorder = &MockOrderSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderSvc) EXPECT() *MockOrderSvcMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockOrderSvc) CreateOrder(ctx context.Context, input dto.CreateOrderReq) dto.CreateOrderRes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, input)
	ret0, _ := ret[0].(dto.CreateOrderRes)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockOrderSvcMockRecorder) CreateOrder(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockOrderSvc)(nil).CreateOrder), ctx, input)
}

// GetOrder mocks base method.
func (m *MockOrderSvc) GetOrder(ctx context.Context, input dto.GetOrderReq) service.PaginationOrderResp {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, input)
	ret0, _ := ret[0].(service.PaginationOrderResp)
	return ret0
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockOrderSvcMockRecorder) GetOrder(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockOrderSvc)(nil).GetOrder), ctx, input)
}

// GetOrderDetail mocks base method.
func (m *MockOrderSvc) GetOrderDetail(ctx context.Context, input dto.GetOrderDetailReq) dto.GetOrderDetailRes {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrderDetail", ctx, input)
	ret0, _ := ret[0].(dto.GetOrderDetailRes)
	return ret0
}

// GetOrderDetail indicates an expected call of GetOrderDetail.
func (mr *MockOrderSvcMockRecorder) GetOrderDetail(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrderDetail", reflect.TypeOf((*MockOrderSvc)(nil).GetOrderDetail), ctx, input)
}
