INSERT INTO book (title, description, author, price) VALUES
('Harry Potter: The Half-Blood Prince', 'The sixth book in the Harry Potter series.', 'J.K. Rowling', 2),
('1984', 'A dystopian social science fiction novel and cautionary tale.', 'George Orwell', 3),
('Pride and Prejudice', 'A romantic novel of manners.', 'Jane Austen', 4),
('To Kill a Mockingbird', 'A novel about racial injustice in the American South.', 'Harper Lee', 2),
('The Great Gatsby', 'A novel about the American dream and the 1920s.', 'F. Scott Fitzgerald', 5),
('Moby Dick', 'A novel about a ship captain''s quest to catch a giant whale.', 'Herman Melville', 6),
('War and Peace', 'A novel that chronicles the French invasion.', 'Leo Tolstoy', 7),
('Hamlet', 'A Shakespearean tragedy about the Prince of Denmark.', 'William Shakespeare', 6),
('The Catcher in the Rye', 'A novel about teenage alienation and loss of innocence.', 'J.D. Salinger', 2),
('The Hobbit', 'A fantasy novel about Bilbo Baggins'' adventure.', 'J.R.R. Tolkien', 5),
('The Lord of the Rings', 'An epic high fantasy novel.', 'J.R.R. Tolkien', 6),
('Ulysses', 'A modernist novel following the life of Leopold Bloom.', 'James Joyce', 8.5),
('Brave New World', 'A dystopian novel about a futuristic society.', 'Aldous Huxley', 2),
('The Adventures of Sherlock Holmes', 'A collection of detective stories.', 'Arthur Conan Doyle', 2),
('The Diary of a Young Girl', 'The writings from the diary written by Anne Frank.', 'Anne Frank',1),
('The Little Prince', 'A poetic tale of a young prince who visits various planets.', 'Antoine de Saint-Exupéry', 5),
('Crime and Punishment', 'A novel about the mental anguish of a young ex-student.', 'Fyodor Dostoevsky', 4),
('Catch-22', 'A satirical war novel about World War II.', 'Joseph Heller', 4),
('Animal Farm', 'A political fable based on the Russian Revolution.', 'George Orwell', 2),
('Jane Eyre', 'A novel about the emotions and experiences of its title character.', 'Charlotte Brontë', 3);
