// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: book.sql

package querier

import (
	"context"

	"github.com/google/uuid"
)

const checkBookExists = `-- name: CheckBookExists :one
SELECT EXISTS(SELECT id FROM "book" WHERE id=$1)
`

func (q *Queries) CheckBookExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, checkBookExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
