// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package querier

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CheckBookExists(ctx context.Context, id uuid.UUID) (bool, error)
	CheckEmailExists(ctx context.Context, email string) (bool, error)
	CheckOrderExists(ctx context.Context, id uuid.UUID) (bool, error)
	CreateBook(ctx context.Context, arg CreateBookParams) (Book, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) (OrderDetail, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	FindBook(ctx context.Context, arg FindBookParams) ([]Book, error)
	FindBookByID(ctx context.Context, id uuid.UUID) (Book, error)
	FindOrderByID(ctx context.Context, arg FindOrderByIDParams) (Order, error)
	FindOrderByUserID(ctx context.Context, arg FindOrderByUserIDParams) ([]Order, error)
	FindOrderDetailByOrderID(ctx context.Context, arg FindOrderDetailByOrderIDParams) ([]FindOrderDetailByOrderIDRow, error)
	FindUserByEmail(ctx context.Context, email string) (User, error)
	GetBookCount(ctx context.Context) (int64, error)
	GetOrderCountByUserId(ctx context.Context, userID uuid.UUID) (int64, error)
	UpdateOrderByID(ctx context.Context, arg UpdateOrderByIDParams) (Order, error)
}

var _ Querier = (*Queries)(nil)
